[input]
base_directory = "."
files = [
    {path = "docs/getting-started.md", url = "/docs/getting-started", title = "Getting Started"},
    {path = "docs/getting-started/adding-scripts.md", url = "/docs/getting-started/adding-scripts", title = "Adding Scripts"},
    {path = "docs/getting-started/style-guide.md", url = "/docs/getting-started/style-guide", title = "Style Guide"},
    {path = "docs/library.md", url = "/docs/library", title = "Library"},
    {path = "docs/library/configuration.md", url = "/docs/library/configuration", title = "Configuration"},
    {path = "docs/library/enigma_string.md", url = "/docs/library/enigma-string", title = "Enigma String"},
    {path = "docs/library/expression.md", url = "/docs/library/expression", title = "Expression"},
    {path = "docs/library/general_library.md", url = "/docs/library/general-library", title = "General Library"},
    {path = "docs/library/note_entry.md", url = "/docs/library/note-entry", title = "Note Entry"},
]

[output]
filename = "static/stork.st"