name: CI

on: [push]

jobs:
    test-push:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12, 14]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.3.1
              with:
                  node-version: ${{ matrix.node }}
            - run: npx pnpm i --frozen-lockfile=false
            - run: npm run lint
            - run: npm run test
